### ISSUE TITLE
elf: add ability to iterate over tables

### ISSUE THREAD

**Issue by rabbitstack** [iovisor/gobpf#101]
Hi, 

I'm wondering if it could be possible to make elf tables (maps) iterable in a similar fashion of those in [bcc](https://github.com/iovisor/bcc/blob/4e04c9456e1a27f567dcdfe8fc3c0b8e1cbf6b5b/tools/biotop.py#L201) framework? I find this feature very useful for polling histograms periodically from user space. If you can provide some general pointers I could prepare a PR for that.

**Comment by alban** [comment]
@rabbitstack That would be useful!

In addition to `LookupElement`, `UpdateElement` etc. in [table.go](https://github.com/iovisor/gobpf/blob/9ec69f06201829737243b07b3211df7c4ae14030/elf/table.go), you would need to add a new method and call the bpf() syscall and use the `BPF_MAP_GET_NEXT_KEY` argument (see [man bpf](http://man7.org/linux/man-pages/man2/bpf.2.html)).

Cilium has an example of doing that with `GetNextKey` in Go too:
https://github.com/cilium/cilium/blob/e49b992/pkg/bpf/map.go#L395-L398

**Comment by rabbitstack** [comment]
@alban My plate is full for the next weeks, but I'll try to give it a try. Thanks for the hints.

**Comment by iaguis** [comment]
Yes, we can close this now. Thanks!

**Comment by rabbitstack** [comment]
I'm trying to replicate `DumpWithCallback` method from Cilium, but I always get `false unable to find next element: no such file or directory`.

```go
      o, _ := ebpfObject("kernel.o")
	mod := bpflib.NewModuleFromReader(bytes.NewReader(o))
	err := mod.Load(nil)
	if err != nil  {
		panic(err)
	}
	if err := mod.EnableKprobes(12); err != nil {
		panic(err)
	}
	m := mod.Map("blkio")
	if m == nil {
		panic("map is nil")
	}

	key := make([]byte, 120)
	nextKey := make([]byte, 120)
	value := make([]byte, 120)
	t := time.NewTicker(time.Second)
	go func() {
		for {
			<-t.C
			for {
				ok, err := mod.LookupNextElement(m, unsafe.Pointer(&key[0]), unsafe.Pointer(&nextKey[0]), unsafe.Pointer(&value[0]))
				if err != nil || !ok {
					break
				}
				copy(key, nextKey)
			}
		}
	}()
```

ebpf program:

```c
#include <linux/kconfig.h>
#include <linux/ptrace.h>
#include <linux/sched.h>
#include <linux/version.h>
#include <linux/bpf.h>
#include <linux/signal.h>
#include <linux/blkdev.h>

#include "include/api.h"

struct bpf_map_def SEC("maps/blkio") blkio = {
	.type = BPF_MAP_TYPE_HASH,
	.key_size = sizeof(u32),
	.value_size = sizeof(u32),
	.max_entries = 20,
	.pinning = 0,
	.namespace = "",
};

SEC("kprobe/blk_account_io_completion")
int kprobe__blk_account_io_completion(struct pt_regs *ctx) {
    unsigned int bytes = (unsigned int) PT_REGS_PARM2(ctx);
    bpf_map_update_elem(&blkio, &bytes, &bytes, BPF_ANY);
    return 0;
}

char _license[] SEC("license") = "GPL";
__u32 _version SEC("version") = 0xFFFFFFFE;
```

What I'm doing wrong?
