### ISSUE TITLE
Module.load() failing with ENOSPC due to too small log buffer

### ISSUE THREAD

**Issue by dswarbrick** [iovisor/gobpf#103]
When trying to load a relatively simple BPF program (one hash, four histograms), Module.load() fails due to a statically configured and too small log buffer:
```go
    logbuf := make([]byte, 65536)
    logbufP := (*C.char)(unsafe.Pointer(&logbuf[0]))
    fd, err := C.bpf_prog_load(uint32(progType), nameCS, start, size, license, version, defaultLogLevel, logbufP, C.uint(len(logbuf)))
```
Doubling the size of the `logbuf` slice or monkey-patching `defaultLogLevel` to be zero allows the program to load.

I haven't seen this issue when trying to load the same BPF program using the Python BCC libs. Either way, it would be great to be able to specify a larger log buffer, or turn off logging, without having to monkey-patch gopbf.

**Comment by dswarbrick** [comment]
For reference, the size of the program which loads successfully using the out-of-the-box `logbuf` size:
```
processed 1200 insns, stack depth 96
```
And when adding the additional few lines of BPF that push it over the limit (and increasing `logbuf` size):
```
processed 1839 insns, stack depth 144
```

**Comment by ravi-kiran** [comment]
I am getting this error because of fixed buffer size 524288 in Module initialization. 

**error while loading \"sched_cls/netdev-ingress\" (no space left on device)**

```
func newModule() *Module {
	return &Module{
		probes:             make(map[string]*Kprobe),
		uprobes:            make(map[string]*Uprobe),
		cgroupPrograms:     make(map[string]*CgroupProgram),
		socketFilters:      make(map[string]*SocketFilter),
		tracepointPrograms: make(map[string]*TracepointProgram),
		schedPrograms:      make(map[string]*SchedProgram),
		log:                make([]byte, 524288),
	}
}
```
It would be nice if log size is a parameter passed into NewModule method.

```
func NewModule(fileName string) *Module {
	module := newModule()
	module.fileName = fileName
	return module
}
```

**Comment by ravi-kiran** [comment]
@schu , The fix here is only for BCC. Can I submit PR for ELF?
