### ISSUE TITLE
Support for symbol lookup

### ISSUE THREAD

**Issue by bobrik** [iovisor/gobpf#113]
In Python it's possible to do `BPF.ksym(ip)` to lookup function name by instruction pointer:

* https://github.com/iovisor/bcc/blob/581052a68e5/src/python/bcc/__init__.py#L1068-L1080

Go should be able to do the same set of lookups.

**Comment by Pryz** [comment]
agree https://github.com/iovisor/gobpf/pull/105 :)

**Comment by bobrik** [comment]
@Pryz did you make that helper package in the end?

**Comment by schu** [comment]
>  never got any response. Let me create a PR quickly with the Ksym func in a helper package to start the discussion.

Sorry, I missed that. Feel free to ping me after a while if you don't get any response :) I'll comment on the pull request.

**Comment by Pryz** [comment]
@schu no worries ! I will ping you next time ;) thanks !

**Comment by schu** [comment]
Was added with #114
