### ISSUE TITLE
Support Attaching Perf Events

### ISSUE THREAD

**Issue by cpg1111** [iovisor/gobpf#129]
I see there's already a PR for this but no review https://github.com/iovisor/gobpf/pull/123 I too have a branch that implements this https://github.com/cpg1111/gobpf/blob/add_perf_event_attach_detach/bcc/module.go#L455, but wish to have this in the mainline version.  Is there a desire to move this along?

**Comment by schu** [comment]
#123 was merged and the bcc module now allows to attach a program to a perf event.
