### ISSUE TITLE
'cannot use &addrC...' problem

### ISSUE THREAD

**Issue by sangyun-han** [iovisor/gobpf#142]
Hello,
I came across this error in running example code.

```
bcc/symbol.go:108: cannot use &addrC (type *C.ulong) as type *C.uint64_t in argument to func literal
```

I followed installation of libbcc.
my linux env is "4.13.0-45-generic #50-Ubuntu SMP Wed May 30 08:23:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
And golang version is 1.8
Please let me know if anyone knows about this issue.
Thanks.

**Comment by owayss** [comment]
Hi @sangyun-han,
The issue is just due to a wrong cgo type conversion in func `bccResolveName`. Check out https://github.com/iovisor/gobpf/pull/148

Cheers!

**Comment by sangyun-han** [comment]
Thanks @owayss 
I will try again when the issue is merged.
