### ISSUE TITLE
Update elf module with new syscall prefixes

### ISSUE THREAD

**Issue by tuxology** [iovisor/gobpf#146]
Our kprobes based syscall framework depends on gobpf's elf module and it worked fine till kernel v4.16. Since 4.17, syscalls have been prefixed with `__x64_` which may be causing the probes to not be inserted by our framework. We need to update the elf module to attach to proper functions by dynamically selecting the syscall name based on the version. A reference is here: https://github.com/iovisor/gobpf/pull/134

You can assign this to me as I am on it

**Comment by rabbitstack** [comment]
@tuxology any progress on this?

**Comment by tuxology** [comment]
@rabbitstack It's awaiting a merge by maintainers. Almost there!

**Comment by rabbitstack** [comment]
@tuxology thanks for the heads up!

I'm experiencing a strange behavior with `__x64_` syscall kprobes. For instance, attaching a kprobe on `__x64_sys_kill` results in an invalid argument values when accessed via `PT_REGS_*` macros (following with the `__x64_sys_kill` example, `signo` is always equal to 0 and the `pid` comes to be a random negative number). Pretty much the same nasty situation is exhibited in other syscalls. Tested on kernel 4.20.11. On kernel 4.15 and with the old syscall naming convention all work as expected.

Any ideas?

**Comment by MaialenUrbieta** [comment]
> @tuxology thanks for the heads up!
> 
> I'm experiencing a strange behavior with `__x64_` syscall kprobes. For instance, attaching a kprobe to `__x64_sys_kill` results in an invalid argument values when accessed via `PT_REGS_*` macros (following with the `__x64_sys_kill` example, `signo` is always equal to 0 and the `pid` comes to be a negative random number). Pretty much the same nasty situation is exhibited in other syscalls. Tested on kernel 4.20.11. On kernel 4.15 and with the old syscall naming convention all work as expected.
> 
> Any ideas?

Years late, but maybe someone out there finds it useful. When using  `__x64_` syscall kprobes you need to access the current tasks pt_regs like so:

```
void handle_pre_kill(struct kprobe *p,struct pt_regs *regs)
{
    struct pt_regs *task_regs = task_pt_regs(current); 
    pid_t pid = task_regs->di;
    int sig = task_regs->si;
}
```
 task_regs->di, task_regs->si will give you the pid and sig value respectively in `__x64_`. Or:
 
 ```
void handle_pre_kill(struct kprobe *p,struct pt_regs *regs)
{
    pid_t pid = ((struct pt_regs*)regs->di)->di;
    int sig = ((struct pt_regs*)regs->di)->si;
    ..    
}
```
Kprobes uses pt_regs to receive parameters and the first parameter has the syscall's pt_reg embedded.
