### ISSUE TITLE
Support reading from debugfs trace pipe

### ISSUE THREAD

**Issue by tuxology** [iovisor/gobpf#19]
Even though we have BPF_PERF_OUTPUT support, It would be nice to have similar support for reading from the debugfs trace pipe the way BCC Supports. Refer [`trace_fields()`](https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#2-trace_fields) support in BCC. This can be useful for quick debugging. This would be the counterpart to `bpf_trace_printk()` in Go

However, do note that BPF_PERF_OUTPUT is the superior approach as it allows handling concurrent traces.

**Comment by schu** [comment]
Done with https://github.com/iovisor/gobpf/pull/25
