### ISSUE TITLE
When run the xdp program having bpf_map,  get errors

### ISSUE THREAD

**Issue by glennWang** [iovisor/gobpf#193]
Would you please add a sample for xdp program having bpf_map ?

I define a struct as the follow, go build is ok, but run it  always give following errors ：

struct bpf_map_def SEC("maps/xsks_map") xsks_map = {
	.type = BPF_MAP_TYPE_XSKMAP,
	.key_size = sizeof(int),
	.value_size = sizeof(int),
	.max_entries = MAX_SOCKS,
	.pinning = 0,
	.namespace = "",
};

/virtual/main.c:15:24: error: expected parameter declarator
struct bpf_map_def SEC("maps/xsks_map") xsks_map = {
                       ^
/virtual/main.c:15:24: error: expected ')'
/virtual/main.c:15:23: note: to match this '('
struct bpf_map_def SEC("maps/xsks_map") xsks_map = {
                      ^
/virtual/main.c:15:41: error: expected function body after function declarator
struct bpf_map_def SEC("maps/xsks_map") xsks_map = {
                                        ^
3 errors generated.

**Comment by glennWang** [comment]
After reading the following document ，I know that bcc has the wrapper of bpf_map_type.

https://github.com/iovisor/bcc/blob/master/docs/reference_guide.md#maps

**Comment by sevagh** [comment]
@glennWang were you able to get XSK maps working using gobpf/bcc? Can you paste the Go and C code here?

**Comment by sevagh** [comment]
Is this related? https://github.com/iovisor/bcc/issues/2460
