### ISSUE TITLE
How to use BPF_PERCPU_ARRAY with gobpf ?

### ISSUE THREAD

**Issue by glennWang** [iovisor/gobpf#194]
The following is the BPF_MAP_TYPE_PERCPU_ARRAY usage demo. But I don't know how to use it with gobpf. Could anyone please make a demo ?

BPF_MAP_TYPE_PERCPU_ARRAY: As above, but kernel programs implicitly write to a per-CPU allocated array which minimizes lock contention in BPF program context. When bpf_map_lookup_elem() is called, it retrieves NR_CPUS values. For example, if we are summing a stat across CPUs, we would do something like this:

                        long values[nr_cpus];
                                                ...

                        ret = bpf_map_lookup_elem(map_fd, &next_key, values);
                        if (ret) {
                                perror("Error looking up stat");
                                continue;
                        }

                        for (i = 0; i < nr_cpus; i++) {
                                sum += values[i];
                        }
Use of a per-cpu data structure is to be preferred in codepaths which are frequently executed, since we will likely be aggregating the results across CPUs in user-space much less frequently than writing updates.

**Comment by rutaka-n** [comment]
Hi. There are no special functions for PERCPU maps, so you can use it in straight-forward way. Just pass array as value.

**Comment by tvsanthoshkumar** [comment]
@rutaka-n 
Do we have any predefined functions like GetP for BPF_MAP_TYPE_PERCPU_ARRAY eBPF Map? If yes, can you point to the correct function?

**Comment by evilsocket** [comment]
```go
import (
 ...
 "github.com/iovisor/gobpf/pkg/cpupossible"
 ...
)

func whatever() {
  ...
  cpus, err := cpupossible.Get()
  if err != nil {
    panic(err)
  }

  data := make([]YourStruct, cpus)
  key := int(0) // depending on your use case

  err := module.LookupElement(yourMap, unsafe.Pointer(&key), unsafe.Pointer(&data[0]))
  if err != nil {
    panic(err)
  }
  
  // here you can merge your data into one
}
```
