### ISSUE TITLE
elf: export nowNanoseconds()?

### ISSUE THREAD

**Issue by mythi** [iovisor/gobpf#213]
This would be a useful function to be exported. 

Example use-case:
BPF code sets a "data updated" timestamp using `bpf_ktime_get_ns()` and at the time of reading the data in Go code, I could say "how long ago the data was updated" using `nowNanoseconds() - bpf_timestamp`.

**Comment by mythi** [comment]
any thoughts?

**Comment by iaguis** [comment]
Exporting it seems reasonable. Do you think you can make a PR? I'll be happy to review it.

**Comment by mythi** [comment]
@iaguis #220 submitted
