### ISSUE TITLE
elf: kprobe loading fails in Debian

### ISSUE THREAD

**Issue by rabbitstack** [iovisor/gobpf#224]
I'm experiencing issues loading the ebpf bytecode from ELF objects in Debian distros. It happens with kernel `4.9.0-11` (Stretch release), but I also was able to reproduce on recent kernel versions, e.g. Debian Buster `4.19.0-6`. 

Here is a bare-minimum reproducer:

test.c
```
#include <linux/kconfig.h>
#include <linux/ptrace.h>

#define SEC(NAME) __attribute__((section(NAME), used))

SEC("kprobe/do_group_exit")
int kprobe__do_group_exit(struct pt_regs *ctx) {
        return 0;
}

char _license[] SEC("license") = "GPL";
__u32 _version SEC("version") = 0xFFFFFFFE;
```

main.go

```
package main

import (

        bpflib "github.com/iovisor/gobpf/elf"
)
func main() {

   mod := bpflib.NewModule("./test.o")
   if mod == nil  {
     panic("nil module")
   }
   if err := mod.Load(nil); err != nil  {
     panic(err)
   }
   if err := mod.EnableKprobe("kprobe/do_group_exit", 1); err != nil {
     panic(err)
   }
}
```

This panics with: `error while loading \"kprobe/do_group_exit\" (invalid argument)"`

I think the kernel has been compiled with sufficient features to support ebpf:

```
CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
# CONFIG_BPF_JIT_ALWAYS_ON is not set
CONFIG_NETFILTER_XT_MATCH_BPF=m
CONFIG_NET_CLS_BPF=m
CONFIG_NET_ACT_BPF=m
CONFIG_BPF_JIT=y
CONFIG_HAVE_EBPF_JIT=y
CONFIG_BPF_EVENTS=y
CONFIG_TEST_BPF=m
```

**Comment by alban** [comment]
I can't reproduce the issue on `5.1.19-300.fc30.x86_64`. Do you know where to get the sources of the Debian kernel you are running? I would check the definition of `do_group_exit` in case it is a static inline function, as opposed to upstream kernels.

Could you also run `strace` to see which syscall returns `invalid argument`? I would like to double-check if it is the `bpf()` syscall or the writing in the `/sys/kernel/debug/tracing/` files that fail in your case.

Misc notes on my test:

<details>

- to test on Linux 5.1, I needed to add the following at the beginning of test.c:
```
#ifdef asm_volatile_goto
#undef asm_volatile_goto
#endif
#define asm_volatile_goto(x...) asm volatile("invalid use of asm_volatile_goto")
```
See also https://github.com/iovisor/bcc/pull/2133/files and https://github.com/iovisor/bcc/pull/2458/files

- to compile, I used the following command:
```
export P=/usr/src/kernels/5.1.19-300.fc30.x86_64/

clang -D__KERNEL__ -D__ASM_SYSREG_H -Wall -O2 -emit-llvm -c test.c -I $P/arch/x86/include -I $P/arch/x86/include/generated -I $P/include -I $P/include/generated/uapi -I $P/arch/x86/include/uapi -I $P/include/uapi -o - | llc -march=bpf -filetype=obj -o test.o

go build -o main main.go
```

</details>

**Comment by rabbitstack** [comment]
Thanks for the quick response. We have switched to Ubuntu and this issue is not manifesting anymore. Previously, I've been loading the same ebpf bytecode in Archlinux 4.20.11 and the minikube Buildroot without problems.

I'll try to spin up an instance of the problematic Debian-based machine and give you some feedback.

Regards

**Comment by rabbitstack** [comment]
Sorry for a long delay. We've just upgraded to the latest gobpf version and the error is gone now.
