### ISSUE TITLE
failed to attach BPF perf event: invalid argument

### ISSUE THREAD

**Issue by weixingsun** [iovisor/gobpf#231]
Hello,

I am trying to write a [profile.py](https://github.com/iovisor/bcc/blob/master/tools/profile.py) in go, python version works properly in my box, but there is a problem in go when attaching to perf event.  I just cannot see which argument is invalid.
Thanks for any comments.

---------------------------------------------------  run it
root@dr1:~/goprofile# go run profile.go
Loaded do_perf_event
ioctl(PERF_EVENT_IOC_SET_BPF) failed: Invalid argument
---------------AttachPerfEvent() type=1, cfg=0 samplePeriod=0 sampleFreq=99
Failed to attach perf event: "failed to attach BPF perf event: invalid argument"

full code here: [profile.go](https://github.com/weixingsun/perf_tuning_results/blob/master/jvm/gojvmti/profile.go)
---------------------------------------------------  snippet
        code := strings.Replace(source, "PID", spid, 1)
        m := bpf.NewModule(code, []string{})
        defer m.Close()
        event, err := m.LoadPerfEvent("do_perf_event")
        if err != nil {
                fmt.Fprintf(os.Stderr, "Failed to load do_perf_event: %s\n", err)
                os.Exit(1)
        }else{
                fmt.Fprintf(os.Stdout, "Loaded do_perf_event\n") //this works
        }
        TYPE :=1    //PERF_TYPE_HARDWARE=0,PERF_TYPE_SOFTWARE=1
        COUNTER:=0  //PERF_COUNT_HW_CPU_CYCLES=0
        PERIOD:=0
        FREQ:=99
        //AttachPerfEvent(evType, evConfig int, samplePeriod int, sampleFreq int, pid, cpu, groupFd, fd int) error
        err = m.AttachPerfEvent(TYPE, COUNTER, PERIOD, FREQ, pid, -1, -1, event)

**Comment by alban** [comment]
I am not sure if it is the issue, but in your code `COUNTER:=0`.
I think it should be `PERF_COUNT_SW_BPF_OUTPUT` instead.
According to `/usr/include/linux/perf_event.h`, `PERF_COUNT_SW_BPF_OUTPUT=10`.

Also, I wonder about `cpu:=1`: do you want only to trace the second CPU, or should it be `cpu:=-1` to trace all cpus?

**Comment by weixingsun** [comment]
@alban thanks for your comments, I did binded this pid to cpu1,
after change COUNTER:=10, it complains as below, is this meaning type1 conflict cfg 10? 
-------------------------
Unable to open or attach perf event for BPF_OUTPUT
Invalid perf event type 1 config 10
-----------------------AttachPerfEvent() type=1, cfg=10 samplePeriod=0 sampleFreq=99
-----------------------failed to attach BPF perf event: <nil>

**Comment by weixingsun** [comment]
in[ libbpf.c](https://github.com/iovisor/bcc/blob/master/src/cc/libbpf.c) the 2 params return invalid from invalid_perf_config() , so  type 1 config 10 is conflict.
I guess type=1, config=0 according to the python version: [profile.py](https://github.com/iovisor/bcc/blob/0cafe5571865d4dcab8ff2bd398b41dbc10b42f4/tools/profile.py#L266)

so that the question back to: ioctl(PERF_EVENT_IOC_SET_BPF) failed: Invalid argument
how to diagnose it? thanks

**Comment by weixingsun** [comment]
I fixed this error by change my kprobe to perf_event, looks like it called the right type lib.load_func and then lib.bpf_attach_perf_event returns properly now, thanks
