### ISSUE TITLE
Incorrect number of arguments in `_Cfunc_bpf_module_create_c_from_string`

### ISSUE THREAD

**Issue by supra08** [iovisor/gobpf#262]
When running the tests or any example, it says that there is an incorrect number of arguments in the `bcc/module.go`'s `_Cfunc_bpf_module_create_c_from_string()` method which appears twice in the file.

**Comment by mauriciovasquezbernal** [comment]
Please see to get more detail on how to solve this problem https://github.com/iovisor/gobpf/issues/255#issuecomment-683750196
