### ISSUE TITLE
Is there any release branch for this repo?

### ISSUE THREAD

**Issue by k82cn** [iovisor/gobpf#279]
Is there any release branch for this repo?

**Comment by dmitris** [comment]
It would be great to add a release - even if v0 one, such as `v0.5.0` - to have a tag that could be used to pin the repo version.

**Comment by schu** [comment]
> Is there any release branch for this repo?

We don't have a release branch, but I pushed a `v0.1.0` tag earlier today and can try to tag a release every once in a while (for example after a new bcc release) if it makes things easier for you. Also, feel free to ping me if you think a release would be due.
