### ISSUE TITLE
Is there any doc about how to build gobpf project?

### ISSUE THREAD

**Issue by wofanli** [iovisor/gobpf#30]
Hi Guys, 

I'm trying gobpf. 
I'm wondering are there any docs or scripts to build gobpf. 

Thanks,
Wenxian

**Comment by schu** [comment]
> I'm wondering are there any docs or scripts to build gobpf.

You can import `github.com/iovisor/gobpf/bcc` or  `github.com/iovisor/gobpf/elf` as any other go library and use it from your programs. See https://github.com/iovisor/gobpf/blob/master/examples/perf.go for an example.

Depending on the eBPF  feature you want to use, you need a (very) recent kernel. A good feature list can be found here: https://github.com/iovisor/bcc/blob/master/docs/kernel-versions.md

**Comment by wofanli** [comment]
@schu Thanks for your quick reply Michael. I can build gobpf now.
