### ISSUE TITLE
Support lost perf event callback

### ISSUE THREAD

**Issue by tuxology** [iovisor/gobpf#41]
I think we need to add the callback in `bpf_open_perf_buffer` [here](https://github.com/iovisor/gobpf/blob/master/bcc/perf.go#L126) for lost events, which has been recently added in BCC. Refer https://github.com/iovisor/bcc/commit/4b764de6bcb3655b29b2fb6df6c9c65b7a31338c I can fix this if you want.

**Comment by alban** [comment]
Yes, thanks :) It could be communicated via a "lostCounter chan uint64" to keep the caller choose in which thread to handle that.

It would be good to add the same support in [github.com/iovisor/gobpf/elf's InitPerfMap](https://github.com/iovisor/gobpf/blob/master/elf/perf.go#L121) too.

In addition to that bcc commit, there is another example doing the same thing on:
https://github.com/cilium/cilium/blob/v0.8.1/pkg/bpf/perf.go#L341-L347

**Comment by schu** [comment]
Thanks :+1: We would have to wait for a new bcc release before merging the update into master.

**Comment by alban** [comment]
https://github.com/iovisor/gobpf/pull/43 added the support in the elf backend, but the support in the bcc backend is still to be done.

**Comment by itaysk** [comment]
this issue should be closed by https://github.com/iovisor/gobpf/pull/235
