### ISSUE TITLE
support for latest bcc version

### ISSUE THREAD

**Issue by rabbitstack** [iovisor/gobpf#85]
gobpf doesn't compile against latest bcc version. More precisely, the following symbols has been changed:

- `bpf_attach_xdp`
- `bcc_resolve_symname` (requires a pointer to `bcc_symbol_option` struct)
-  `bpf_open_perf_buffer` (needs a pointer to `perf_reader_lost_cb` function)

**Comment by schu** [comment]
[We support the latest released version](https://github.com/iovisor/gobpf#githubcomiovisorgobpfbcc) of bcc, currently v0.3.0. Once v0.4.0 is out, we'll update to the new signatures (see also https://github.com/iovisor/gobpf/pull/73).

**Comment by omac777** [comment]
What do we need to do for the interim?  Is there a particular bcc git tag we should download and build in order to successfully build gobpf?
