### ISSUE TITLE
statically linking go binaries against lbcc

### ISSUE THREAD

**Issue by rabbitstack** [iovisor/gobpf#86]
Is it possible to statically link gobpf binary against libbcc? I'm trying to accomplish that with perf.go example and there's no way (compiler is complaining about undefined symbols from llvm, stdlibc++, etc). I'm using the following command:

`go build -ldflags "-extldflags -static"  perf.go `

**Comment by alban** [comment]
I don't know how to do that...
Static linking would be easier by using the elf backend rather than the libbcc one. I've seen your issue on the elf backend in #101; is it why you tried this one?

**Comment by rabbitstack** [comment]
Actually, ELF based ebpf bytecode loading did the job for me. Linking against libbcc is a real PITA. I'll close this issue.

**Comment by rockmenjack** [comment]
@ rabbitstack  could you please share the your workaround for avoiding libbcc?

**Comment by rabbitstack** [comment]
@rockmenjack unfortunately, no workaround here. I gave up trying to produce a statically-linked binary against libbcc (requires way too much dependencies such as clang, llvm, etc.). I'm shipping the eBPF bytecode inside the binary and loading it directly via ELF modules.

**Comment by dswarbrick** [comment]
@rabbitstack How do you deal with different kernel versions when shipping precompiled eBPF bytecode? Or do you only target a single kernel version?

**Comment by rabbitstack** [comment]
I didn't experience any issues while compiling eBPF programs on one kernel version and then loading the bytecode on a different kernel. In reality, I mostly deal with kprobes on syscall interface, which is guaranteed to remain stable among kernel versions (actually, there was a breaking change in gobpf due to naming changes in syscall functions introduced in kernel 4.17, but it was addressed recently even for ELF modules).
