### ISSUE TITLE
Table Entry vs Get/Set/Delete

### ISSUE THREAD

**Issue by Pryz** [iovisor/gobpf#89]
Hi there,

Based on the doc, I was expected to be able to do things like : 
```
for e := range table.Iter() {
  ...
  table.Delete(e.Key)
}
```

But I am getting this error : 
```
Table.Delete: unable to delete element ({ 0xffffffff88dbecd1 }): no such file or directory
```
I'm not sure what I'm missing here. I'm using a `BPF_HASH`.
What's the difference between `keyStr` from [Get](https://godoc.org/github.com/iovisor/gobpf/bcc#Table.Get) or Delete/Set and `Key` of an [Entry](https://godoc.org/github.com/iovisor/gobpf/bcc#Entry) ?

Thanks !

**Comment by schu** [comment]
Hey, `table.Iter()` uses [bpf_table_key_snprintf](https://github.com/iovisor/gobpf/blob/master/bcc/table.go#L204) for the key which returns a string representation of the key according to the key type of the table (https://github.com/iovisor/bcc/blob/91837cacfbe74141d88efcd096ff8d33a1517d2d/src/cc/bpf_module.cc#L515-L516)

The `table.Iter()`/`table.Entry` usage has led to confusion in the past. I would also like to see this changed to something more straightforward.

**Comment by schu** [comment]
So for the time being you somehow have to find your way around that to delete all entries.

**Comment by Pryz** [comment]
Make sense. Any thought about https://github.com/iovisor/gobpf/pull/91 ?
