### ISSUE TITLE
when i compile, i occured bcc_foreach_symbol not found

### ISSUE THREAD

**Issue by carolove** [iovisor/gobpf#94]
https://github.com/iovisor/gobpf/blob/9741b4d66cf77f649e9881da47d8f1dc7731cb83/bcc/symbol.go#L94

issue:
compile output:
 ../../../gobpf/bcc/symbol.go:94:9: could not determine kind of name for C.bcc_foreach_symbol

env:
machine: macbook pro
os: ubuntu 16.04
kernel: 4.10.0-37-generic

ops:
1\ follow Installing Hover 
2\ execute, go install github.com/iovisor/iomodules/hover/hoverd

**Comment by schu** [comment]
The update to bcc release v0.4.0 was not yet merged. It is now and the issue should be gone (`bcc_foreach_symbol` was renamed to `bcc_foreach_function_symbol`).
