### ISSUE TITLE
go get github.com/iovisor/gobpf/bcc fails

### ISSUE THREAD

**Issue by cpg1111** [iovisor/gobpf#98]
Hi there,
Currently, when I run `go get github.com/iovisor/gobpf/bcc` I receive this error:

    bcc/module.go:175: not enough arguments in call to _C2func_bpf_prog_load
        have (uint32, *C.struct_bpf_insn, C.int, *C.char, C.uint, *C.char, C.uint)
        want (uint32, *C.char, *C.struct_bpf_insn, C.int, *C.char, C.uint, C.int, *C.char, C.uint)

I have a PR that fixes this: https://github.com/iovisor/gobpf/pull/97, however, I'm not sure how to handle the log level argument, and feedback would be greatly appreciated.

**Comment by schu** [comment]
With the release of bcc 0.5.0 and https://github.com/iovisor/gobpf/pull/100 this should be fixed.
